name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: [18, 19]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Set React version
        run: npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}
      - name: Run tests
        run: npm test
